name: Gestor de Despesas UTMify

on:
  schedule:
    # O GitHub vai acionar este robô automaticamente a cada 20 minutos
    - cron: '*/20 * * * *' 
  workflow_dispatch: # Botão de Play Manual

jobs:
  run-despesas:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar Playwright e Dependências
        run: |
          pip install playwright
          playwright install chromium
          
      - name: Rodar Script de Gastos
        run: python gestor_despesas.py
